/* ================================================================
   Catálogo de productos — Sabores de Monte
   TODO: reemplazar con consulta a Supabase cuando esté configurado
   ================================================================ */

export const products = [

  /* ─────────────────────── MIEL ─────────────────────── */
  {
    id:               "miel-multifloral",
    nombre:           "Miel Multifloral",
    categoria:        "miel",
    descripcion:      "Miel multifloral de las sierras de Córdoba. Extracción propia, sin pasteurizar ni filtrar.",
    descripcionLarga: "Cosechada en el corazón del monte cordobés, nuestra Miel Multifloral es el resultado de la visita de las abejas a más de treinta especies florales silvestres. Se extrae en frío, sin pasteurizar ni filtrar, conservando intactos todos sus enzimas, polifenoles y propiedades naturales. Su sabor es complejo y aromático, con notas florales que varían levemente según la temporada de cosecha.",
    origen:           "Obispo Trejo, Córdoba",
    presentaciones:   ["500 g", "1 kg", "5 kg", "20 kg"],
    badge:            "Producto principal",
    imagen:           "/img/miel/miel-1.png",
    imageAlt:         "Tarro de Miel Multifloral natural Sabores de Monte, Obispo Trejo, Córdoba",
    beneficios: [
      { icono: "Leaf",       texto: "100% natural, sin conservantes ni aditivos" },
      { icono: "Shield",     texto: "Propiedades antibacterianas certificadas" },
      { icono: "Zap",        texto: "Fuente de energía de liberación lenta" },
      { icono: "Heart",      texto: "Fortalece el sistema inmunológico" },
      { icono: "Droplets",   texto: "Hidrata y protege la mucosa de garganta" },
      { icono: "Award",      texto: "Sin pasteurizar — enzimas activos intactos" },
    ],
  },
  {
    id:               "miel-citrus",
    nombre:           "Miel de Citrus",
    categoria:        "miel",
    descripcion:      "Miel monofloral proveniente de flores de naranjo y limonero. Sabor suave y muy aromático.",
    descripcionLarga: "Obtenida de colmenas ubicadas en zonas de alta concentración de cítricos, esta miel monofloral se distingue por su color claro y su aroma delicado a azahar. Ideal para preparaciones dulces, infusiones y maridaje con quesos frescos. Se extrae en período de floración de naranjo, entre agosto y octubre.",
    origen:           "Obispo Trejo, Córdoba",
    presentaciones:   ["500 g", "1 kg", "5 kg"],
    badge:            "Temporada",
    imagen:           "/img/miel/miel-2.png",
    imageAlt:         "Miel de Citrus clara y aromática de Sabores de Monte",
    beneficios: [
      { icono: "Leaf",       texto: "Monofloral de naranjo — perfil aromático único" },
      { icono: "Shield",     texto: "Propiedades antioxidantes del azahar" },
      { icono: "Heart",      texto: "Ideal para digestión y relajación" },
      { icono: "Droplets",   texto: "Color claro, textura fluida y delicada" },
    ],
  },
  {
    id:               "miel-cremada",
    nombre:           "Miel Cremada",
    categoria:        "miel",
    descripcion:      "Miel batida artesanalmente hasta lograr una textura cremosa y suave. No se derrama.",
    descripcionLarga: "A través de un proceso de batido lento y controlado a baja temperatura, logramos una miel con textura de manteca suave, perfecta para untar. La cristalización dirigida no altera ninguna de sus propiedades naturales — simplemente cambia la forma. Ideal para el sector gastronómico y para packaging diferenciado.",
    origen:           "Obispo Trejo, Córdoba",
    presentaciones:   ["250 g", "500 g", "1 kg"],
    badge:            "Gourmet",
    imagen:           "/img/miel/miel-3.png",
    imageAlt:         "Miel Cremada artesanal Sabores de Monte, textura suave para untar",
    beneficios: [
      { icono: "Star",       texto: "Textura cremosa ideal para gastronomía" },
      { icono: "Leaf",       texto: "Mismas propiedades que la miel líquida" },
      { icono: "Package",    texto: "No se derrama — perfecta para transporte" },
      { icono: "Heart",      texto: "Proceso artesanal a baja temperatura" },
    ],
  },
  {
    id:               "miel-propoleos",
    nombre:           "Miel con Propóleos",
    categoria:        "miel",
    descripcion:      "Miel natural enriquecida con extracto de propóleos de la propia colmena. Potente y defensiva.",
    descripcionLarga: "Los propóleos son la resina que las abejas recolectan para proteger la colmena de bacterias y hongos. Combinados con nuestra miel multifloral, generan un producto de alto valor funcional reconocido por la medicina natural. Con sabor más intenso y terroso, este producto tiene alta rotación en tiendas naturistas y farmacias.",
    origen:           "Obispo Trejo, Córdoba",
    presentaciones:   ["250 g", "500 g"],
    badge:            "Funcional",
    imagen:           "/img/miel/miel-1.png",
    imageAlt:         "Miel con Propóleos Sabores de Monte, producto natural defensivo",
    beneficios: [
      { icono: "Shield",     texto: "Propóleos: antimicrobiano natural potente" },
      { icono: "Heart",      texto: "Refuerza las defensas del organismo" },
      { icono: "Leaf",       texto: "Sin conservantes — 100% productos de colmena" },
      { icono: "Zap",        texto: "Alta demanda en canal naturista y farmacias" },
    ],
  },

  /* ─────────────────────── SALES ─────────────────────── */
  {
    id:               "sal-original",
    nombre:           "Sal de Campo Original",
    categoria:        "sal",
    descripcion:      "Blend clásico de sal gruesa con hierbas del campo. Versátil para todo tipo de carnes y verduras.",
    descripcionLarga: "La sal original es el blend con el que empezamos. Una combinación equilibrada de sal gruesa con hierbas aromáticas del campo argentino: orégano, tomillo, romero y ají molido. Pensada para el asado, las verduras a la parrilla y la cocina de todos los días. Sin TACC, sin conservantes ni aditivos artificiales.",
    origen:           "Argentina",
    presentaciones:   ["250 g"],
    badge:            "Sin TACC",
    imagen:           "/img/sal/sal-1.png",
    imageAlt:         "Sal de Campo Original Sabores de Monte, blend artesanal con hierbas",
    beneficios: [
      { icono: "Leaf",       texto: "Sin conservantes ni aditivos artificiales" },
      { icono: "ShieldCheck",texto: "Libre de TACC — apta celíacos" },
      { icono: "ChefHat",    texto: "Blend artesanal de hierbas del campo" },
      { icono: "Flame",      texto: "Ideal para asados, parrilla y verduras" },
    ],
  },
  {
    id:               "sal-fina",
    nombre:           "Sal Fina con Hierbas",
    categoria:        "sal",
    descripcion:      "Sal fina molida con hierbas frescas deshidratadas. Textura fluida para salsas y aderezos.",
    descripcionLarga: "La misma fórmula del blend original pero con sal fina molida, pensada para salsas, aderezos, marinadas y terminaciones de platos. Su textura uniforme la hace perfecta para saleros de mesa y cocina de autor. Ideal para restaurantes y cocinas profesionales.",
    origen:           "Argentina",
    presentaciones:   ["250 g"],
    badge:            "Sin TACC",
    imagen:           "/img/sal/sal-2.png",
    imageAlt:         "Sal Fina con Hierbas Sabores de Monte, para salsas y aderezos",
    beneficios: [
      { icono: "Leaf",       texto: "Sin conservantes ni aditivos artificiales" },
      { icono: "ShieldCheck",texto: "Libre de TACC" },
      { icono: "ChefHat",    texto: "Textura fina ideal para aderezos y salsas" },
      { icono: "Star",       texto: "Perfecta para cocina de autor y gastronomía" },
    ],
  },
  {
    id:               "sal-ahumada",
    nombre:           "Sal Ahumada",
    categoria:        "sal",
    descripcion:      "Sal ahumada lentamente con maderas naturales. Aporta profundidad y un toque ahumado inconfundible.",
    descripcionLarga: "Elaborada con sal gruesa sometida a un proceso de ahumado lento con maderas naturales seleccionadas. Aporta un sabor profundo y complejo, ideal para carnes rojas, pollo, pastas y quesos. Muy valorada en cocina gourmet y restaurantes que buscan diferenciación en sus preparaciones.",
    origen:           "Argentina",
    presentaciones:   ["250 g"],
    badge:            "Sin TACC",
    imagen:           "/img/sal/sal-3.png",
    imageAlt:         "Sal Ahumada artesanal Sabores de Monte, ahumado con maderas naturales",
    beneficios: [
      { icono: "Flame",      texto: "Ahumado con maderas naturales seleccionadas" },
      { icono: "ShieldCheck",texto: "Sin TACC, sin aditivos" },
      { icono: "Star",       texto: "Muy valorada en cocina gourmet" },
      { icono: "ChefHat",    texto: "Ideal para carnes rojas, pollo y quesos" },
    ],
  },
  {
    id:               "sal-marina",
    nombre:           "Sal Marina con Algas",
    categoria:        "sal",
    descripcion:      "Sal marina con algas deshidratadas. Rica en minerales y yodo natural. Perfecta para pescados.",
    descripcionLarga: "Combinación de sal marina gruesa con algas marinas deshidratadas ricas en minerales, yodo natural y sabor oceánico. Ideal para pescados, mariscos, sushi y cocina oriental. Su perfil mineral la diferencia claramente de las sales comunes.",
    origen:           "Argentina",
    presentaciones:   ["250 g"],
    badge:            "Sin TACC",
    imagen:           "/img/sal/sal-4.png",
    imageAlt:         "Sal Marina con Algas Sabores de Monte, rica en minerales y yodo natural",
    beneficios: [
      { icono: "Droplets",   texto: "Rica en minerales y yodo natural de algas" },
      { icono: "ShieldCheck",texto: "Sin TACC, sin conservantes" },
      { icono: "Leaf",       texto: "Algas deshidratadas 100% naturales" },
      { icono: "ChefHat",    texto: "Perfecta para pescados, mariscos y cocina oriental" },
    ],
  },
  {
    id:               "sal-picante",
    nombre:           "Sal Picante",
    categoria:        "sal",
    descripcion:      "Blend de sal con ají molido, pimentón y especias. Para los amantes del picante.",
    descripcionLarga: "Para los que no pueden imaginar un asado sin fuego. Este blend combina sal gruesa con ají molido, pimentón ahumado, cayena y un toque de pimienta negra. Perfecta para carnes, pollo, marinadas y salsas con carácter. Picante equilibrado, que acompaña sin dominar.",
    origen:           "Argentina",
    presentaciones:   ["250 g"],
    badge:            "Picante",
    imagen:           "/img/sal/sal-5.png",
    imageAlt:         "Sal Picante Sabores de Monte, blend con ají molido y especias",
    beneficios: [
      { icono: "Flame",      texto: "Blend con ají, pimentón ahumado y cayena" },
      { icono: "ShieldCheck",texto: "Sin TACC, sin conservantes" },
      { icono: "ChefHat",    texto: "Ideal para marinadas y carnes a la parrilla" },
      { icono: "Zap",        texto: "Picante equilibrado, que acompaña sin dominar" },
    ],
  },
  {
    id:               "sal-limon-pimienta",
    nombre:           "Sal Limón y Pimienta",
    categoria:        "sal",
    descripcion:      "Combinación fresca y cítrica. Limón deshidratado, pimienta negra y sal gruesa.",
    descripcionLarga: "La frescura del limón deshidratado con la intensidad de la pimienta negra molida gruesa. Un clásico de la cocina mediterránea adaptado a los sabores del campo argentino. Excelente para pollo, ensaladas, papas y pescados. Alta aceptación en el canal gourmet y hoteles.",
    origen:           "Argentina",
    presentaciones:   ["250 g"],
    badge:            "Sin TACC",
    imagen:           "/img/sal/sal-6.png",
    imageAlt:         "Sal Limón y Pimienta Sabores de Monte, blend cítrico artesanal",
    beneficios: [
      { icono: "Leaf",       texto: "Limón deshidratado natural, sin esencias" },
      { icono: "ShieldCheck",texto: "Sin TACC, sin aditivos artificiales" },
      { icono: "ChefHat",    texto: "Ideal para pollo, papas y ensaladas" },
      { icono: "Star",       texto: "Alta aceptación en hoteles y cocina gourmet" },
    ],
  },
  {
    id:               "sal-provenzal",
    nombre:           "Sal Provenzal",
    categoria:        "sal",
    descripcion:      "Clásico mix de sal con ajo, perejil y hierbas provenzales. El favorito para la parrilla.",
    descripcionLarga: "La combinación que nunca falla. Sal gruesa con ajo deshidratado, perejil, tomillo, romero y orégano al estilo provenzal. Un clásico de la gastronomía argentina que nunca pasa de moda. Alta rotación en distribuidoras, restaurantes y supermercados gourmet.",
    origen:           "Argentina",
    presentaciones:   ["250 g"],
    badge:            "Clásico",
    imagen:           "/img/sal/sal-7.png",
    imageAlt:         "Sal Provenzal Sabores de Monte, mix artesanal con ajo y hierbas",
    beneficios: [
      { icono: "Leaf",       texto: "Ajo y hierbas provenzales deshidratados naturalmente" },
      { icono: "ShieldCheck",texto: "Sin TACC, sin conservantes" },
      { icono: "Flame",      texto: "El clásico infaltable en la parrilla argentina" },
      { icono: "ChefHat",    texto: "Alta rotación en distribuidoras y gastronomía" },
    ],
  },
  {
    id:               "sal-curry",
    nombre:           "Sal con Curry",
    categoria:        "sal",
    descripcion:      "Blend exótico de sal con curry, cúrcuma y especias orientales. Para platos con carácter.",
    descripcionLarga: "Un blend que fusiona la tradición oriental con la cocina argentina. Sal gruesa con curry en polvo, cúrcuma, comino y cilantro. Ideal para arroces, pollo, vegetales asados y recetas de cocina fusión. Muy bien recibido en restaurantes de cocina creativa y tiendas gourmet.",
    origen:           "Argentina",
    presentaciones:   ["250 g"],
    badge:            "Sin TACC",
    imagen:           "/img/sal/sal-8.png",
    imageAlt:         "Sal con Curry Sabores de Monte, blend exótico con cúrcuma y especias",
    beneficios: [
      { icono: "Leaf",       texto: "Cúrcuma natural con propiedades antiinflamatorias" },
      { icono: "ShieldCheck",texto: "Sin TACC, sin aditivos" },
      { icono: "ChefHat",    texto: "Ideal para arroces, pollo y cocina fusión" },
      { icono: "Star",       texto: "Muy valorado en restaurantes creativos y gourmet" },
    ],
  },

  /* ─────────────────────── AJO & ACEITE ─────────────────────── */
  {
    id:               "ajo-polvo-natural",
    nombre:           "Ajo en Polvo Natural",
    categoria:        "ajo-aceite",
    descripcion:      "Ajo 100% deshidratado y molido. Sin aglomerantes ni conservantes. Sabor concentrado.",
    descripcionLarga: "Elaborado únicamente con dientes de ajo seleccionados, deshidratados lentamente y molidos en su punto justo. Sin aglomerantes, sin conservantes, sin ningún aditivo. El ajo en polvo más puro del mercado, con un sabor concentrado que rinde mucho más que el ajo fresco picado. Ideal para rubs, marinadas, salsas y cocina profesional.",
    origen:           "Argentina",
    presentaciones:   ["100 g", "250 g", "500 g"],
    badge:            "Sin TACC",
    imagen:           "/img/Ajo en Polvo/ajo-1.png",
    imageAlt:         "Ajo en Polvo Natural Sabores de Monte, 100% deshidratado sin aditivos",
    beneficios: [
      { icono: "Leaf",       texto: "100% ajo deshidratado, sin aglomerantes" },
      { icono: "Shield",     texto: "Rico en allicina — propiedades antibacterianas" },
      { icono: "ShieldCheck",texto: "Sin TACC, sin conservantes ni aditivos" },
      { icono: "Zap",        texto: "Sabor concentrado, rinde más que ajo fresco" },
      { icono: "ChefHat",    texto: "Ideal para rubs, marinadas y cocina profesional" },
    ],
  },
  {
    id:               "ajo-polvo-ahumado",
    nombre:           "Ajo en Polvo Ahumado",
    categoria:        "ajo-aceite",
    descripcion:      "Ajo deshidratado con un toque de ahumado natural. Profundidad y carácter en cada preparación.",
    descripcionLarga: "El ajo en polvo tradicional llevado a otro nivel. Sometemos el ajo deshidratado a un proceso de ahumado con maderas naturales antes del molido, logrando un perfil de sabor profundo y complejo. Muy buscado por chefs y cocineros que buscan ese diferencial ahumado sin necesidad de parrilla.",
    origen:           "Argentina",
    presentaciones:   ["100 g", "250 g"],
    badge:            "Gourmet",
    imagen:           "/img/Ajo en Polvo/ajo-2.png",
    imageAlt:         "Ajo en Polvo Ahumado Sabores de Monte, sabor profundo y complejo",
    beneficios: [
      { icono: "Flame",      texto: "Ahumado con maderas naturales seleccionadas" },
      { icono: "Leaf",       texto: "Sin aglomerantes ni conservantes" },
      { icono: "ShieldCheck",texto: "Sin TACC" },
      { icono: "Star",       texto: "Muy valorado por chefs y cocina profesional" },
    ],
  },
  {
    id:               "ajo-granulado",
    nombre:           "Ajo Granulado",
    categoria:        "ajo-aceite",
    descripcion:      "Ajo deshidratado en granulado grueso. Textura que se nota en el plato. Sin polvos ni grumos.",
    descripcionLarga: "Para quienes prefieren sentir la textura del ajo en cada bocado. El granulado grueso se incorpora mejor a adobos, salsas rústicas y rubs para carnes. Se mezcla más fácilmente con sal gruesa y otros condimentos. Una alternativa al polvo fino para cocineros que buscan diferencia de textura.",
    origen:           "Argentina",
    presentaciones:   ["100 g", "250 g"],
    badge:            "Sin TACC",
    imagen:           "/img/Ajo en Polvo/ajo-3.png",
    imageAlt:         "Ajo Granulado Sabores de Monte, textura gruesa para adobos y rubs",
    beneficios: [
      { icono: "Leaf",       texto: "Granulado grueso, sin aditivos ni aglomerantes" },
      { icono: "ShieldCheck",texto: "Sin TACC" },
      { icono: "ChefHat",    texto: "Ideal para adobos, rubs y salsas rústicas" },
      { icono: "Zap",        texto: "Se mezcla mejor con sal gruesa y otros condimentos" },
    ],
  },
  {
    id:               "aceite-oliva-unico",
    nombre:           "Aceite de Oliva ÚNICO",
    categoria:        "ajo-aceite",
    descripcion:      "Aceite de Oliva Virgen Extra con Ajo Negro líquido. Primera presión en frío. 500 ml.",
    descripcionLarga: "ÚNICO es nuestra línea premium de aceite de oliva. Un Virgen Extra de primera presión en frío al que incorporamos ajo negro líquido — un fermentado natural de ajo que potencia el sabor y aporta una suavidad única. Sin mezclas con aceites de semilla. Ideal para el canal gourmet, hoteles cinco estrellas y restaurantes de alta cocina.",
    origen:           "Argentina",
    presentaciones:   ["500 ml"],
    badge:            "Premium",
    imagen:           "/img/oliva/oliva-1.png",
    imageAlt:         "Aceite de Oliva ÚNICO con Ajo Negro Sabores de Monte, Virgen Extra premium",
    beneficios: [
      { icono: "Award",      texto: "Virgen Extra de primera presión en frío" },
      { icono: "Droplets",   texto: "Alto contenido en ácido oleico y polifenoles" },
      { icono: "Leaf",       texto: "Sin mezcla con aceites de semilla" },
      { icono: "Star",       texto: "Ajo negro fermentado — sabor suave y profundo" },
      { icono: "Heart",      texto: "Propiedades cardiovasculares del AOVE" },
    ],
  },
  {
    id:               "aceite-ajo-negro",
    nombre:           "AOVE Ajo Negro Macerado",
    categoria:        "ajo-aceite",
    descripcion:      "Aceite de Oliva Virgen Extra macerado con Ajo Negro entero. Sin conservantes ni colorantes.",
    descripcionLarga: "A diferencia del ÚNICO donde el ajo negro es líquido, en esta variante maceramos el ajo negro entero dentro del aceite durante semanas, logrando una infusión lenta y profunda. El resultado es un aceite con aroma intenso, sabor redondo y una suavidad llamativa para ser un producto con ajo. Muy buscado en tiendas gourmet y como regalo corporativo.",
    origen:           "Argentina",
    presentaciones:   ["250 ml", "Pack ×6"],
    badge:            null,
    imagen:           "/img/oliva/oliva-2.png",
    imageAlt:         "AOVE Ajo Negro Macerado Sabores de Monte, infusión lenta y profunda",
    beneficios: [
      { icono: "Droplets",   texto: "Maceración lenta — sabor redondo e intenso" },
      { icono: "Award",      texto: "Virgen Extra, sin mezclas ni aditivos" },
      { icono: "Leaf",       texto: "Ajo negro con propiedades antioxidantes únicas" },
      { icono: "Star",       texto: "Ideal para regalo corporativo y tiendas gourmet" },
    ],
  },
  {
    id:               "aceite-oliva-clasico",
    nombre:           "Aceite de Oliva Clásico",
    categoria:        "ajo-aceite",
    descripcion:      "Aceite de Oliva Virgen Extra puro. Sin infusiones. Sabor limpio, frutado y equilibrado.",
    descripcionLarga: "Para quienes buscan un AOVE sin agregados, con el sabor limpio y frutado del olivo en su estado puro. Primera presión en frío, sin mezclas con aceites de semilla, con un perfil sensorial equilibrado que lo hace versátil para cualquier preparación: desde una ensalada hasta una fritura. Nuestro volumen de venta más alto en el canal mayorista.",
    origen:           "Argentina",
    presentaciones:   ["500 ml", "1 L"],
    badge:            null,
    imagen:           "/img/oliva/oliva-3.png",
    imageAlt:         "Aceite de Oliva Virgen Extra Clásico Sabores de Monte, puro y frutado",
    beneficios: [
      { icono: "Award",      texto: "Virgen Extra de primera presión en frío" },
      { icono: "Droplets",   texto: "Sabor limpio, frutado y equilibrado" },
      { icono: "Heart",      texto: "Rico en ácidos grasos monoinsaturados" },
      { icono: "Leaf",       texto: "Sin mezclas, sin conservantes, sin aditivos" },
    ],
  },
];

/* ─── Categorías para los filtros del catálogo ─── */
export const categories = [
  { value: "todos",     label: "Todos"          },
  { value: "miel",      label: "Miel"            },
  { value: "sal",       label: "Sales"           },
  { value: "ajo-aceite",label: "Ajo & Aceite"    },
];

/* ─── Labels legibles de categoría ─── */
export const categoryLabels = {
  miel:       "Miel",
  sal:        "Sales",
  "ajo-aceite": "Ajo & Aceite de Oliva",
};
